FROM python:3.9

# Copy token retrieval script into the container
COPY ./token_retrieval_script.py /app/token_retrieval_script.py

# Install dependencies if needed
 RUN pip install requests

# Run the token retrieval script when the container starts
CMD ["python", "/app/token_retrieval_script.py"]
